theme: minima
title: Here's my first Blog
author: Vishwanath Pratap Singh
email: vishnupsingh523@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an enthusiastic front-end web developer. At present I am working on the intergration of Python and RedHat-8 and I am also improving my skills on Data Structure and Algorithms.
   And at present I am persuing B. Tech Computer Science Engineering from Lovely Professional University. I am  <b>2 Star coder at Codechef</b> and I'm also having an newbie rank in Codeforces.
   

# social links
twitter_username: vishnupsingh522 # DO NOT include the @ character, or else the build will fail!
github_username:  vishnupsingh523 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
